
# See: https://starship.rs/config/#prompt
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$character
"""

[hostname]
ssh_only = false

[directory]
# truncate_to_repo = false
